# Generated by Django 5.1.6 on 2025-02-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0003_session_enrollmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='EnrollmentRequest',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
