# Generated by Django 5.1.6 on 2025-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0004_remove_session_teacher_delete_enrollmentrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
