# Generated by Django 5.1.6 on 2025-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0006_rename_is_student_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
