# Generated by Django 5.1.6 on 2025-03-13 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0008_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pending_students',
            field=models.ManyToManyField(blank=True, related_name='pending_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
