# Generated by Django 5.1.6 on 2025-04-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0015_remove_question_created_at_remove_question_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_limit_minutes',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(default='A'),
        ),
        migrations.AddField(
            model_name='question',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='Hi'),
        ),
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='num_mcq',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='test',
            name='num_qna',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='In minutes'),
        ),
        migrations.AddField(
            model_name='test',
            name='topic_file',
            field=models.FileField(blank=True, null=True, upload_to='test_files/'),
        ),
        migrations.AddField(
            model_name='test',
            name='topic_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('qna', 'QnA'), ('mcq', 'MCQ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
