# Generated by Django 5.1.6 on 2025-04-17 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0016_rename_title_test_name_remove_question_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='test',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='test',
            name='num_mcq',
        ),
        migrations.RemoveField(
            model_name='test',
            name='num_qna',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='test',
            name='topic_file',
        ),
        migrations.RemoveField(
            model_name='test',
            name='topic_text',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default='Hi'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='smartassess.session'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('QNA', 'Written Answer')], default='MCQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartassess.test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartassess.test')),
            ],
        ),
    ]
