# Generated by Django 5.1.6 on 2025-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0021_practiceresult_practicequestionresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceresult',
            old_name='out_of',
            new_name='total_score',
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='overall_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='suggested_topics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='ai_feedback',
            field=models.TextField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='practicequestionresult',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
