# Generated by Django 5.1.6 on 2025-05-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0024_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='total_questions',
        ),
    ]
