# Generated by Django 5.1.6 on 2025-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0025_remove_testattempt_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
