# Generated by Django 5.1.6 on 2025-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartassess', '0026_testattempt_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
